"""
/init 命令 - 初始化项目 / Initialize project
"""

from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel

console = Console()


def init_slash_command(args: list, obj: dict, session_manager, registry, **kwargs) -> None:
    """
    初始化项目 / Initialize project
    
    用法 / Usage: /init
    """
    cwd = Path.cwd()
    claude_md = cwd / "CLAUDE.md"
    
    if claude_md.exists():
        console.print(f"[green]CLAUDE.md 已存在 / CLAUDE.md already exists[/green]")
        if not Confirm.ask("是否覆盖？ / Overwrite?", default=False):
            return
    
    console.print(Panel(
        "[bold cyan]项目初始化 / Project Initialization[/bold cyan]\n\n"
        "将创建 CLAUDE.md 文件，包含项目指南和上下文信息\n"
        "Will create CLAUDE.md file with project guidelines and context",
        border_style="cyan"
    ))
    
    project_name = Prompt.ask(
        "项目名称 / Project name",
        default=cwd.name
    )
    
    description = Prompt.ask(
        "项目描述 / Project description",
        default=""
    )
    
    content = f"""# {project_name}

{description}

## 项目结构 / Project Structure

此项目使用 AloneChat 进行开发。
This project is developed using AloneChat.

## 开发指南 / Development Guidelines

- 遵循代码风格规范 / Follow code style guidelines
- 编写清晰的注释 / Write clear comments
- 保持代码简洁 / Keep code simple

## 技术栈 / Tech Stack

- Python 3.10+
- AloneChat CLI

---
*由 AloneChat 自动生成 / Generated by AloneChat*
"""
    
    claude_md.write_text(content, encoding="utf-8")
    console.print(f"\n[green]✓ 已创建 / Created: {claude_md}[/green]")
