"""
/init å½ä»¤ - åå§åé¡¹ç?/ Initialize project
"""

from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel

console = Console()


def init_slash_command(args: list, obj: dict, session_manager, registry, **kwargs) -> None:
    """
    åå§åé¡¹ç?/ Initialize project
    
    ç¨æ³ / Usage: /init
    """
    cwd = Path.cwd()
    claude_md = cwd / "CLAUDE.md"
    
    if claude_md.exists():
        console.print(f"[green]CLAUDE.md å·²å­å?/ CLAUDE.md already exists[/green]")
        if not Confirm.ask("æ¯å¦è¦çï¼?/ Overwrite?", default=False):
            return
    
    console.print(Panel(
        "[bold cyan]é¡¹ç®åå§å?/ Project Initialization[/bold cyan]\n\n"
        "å°åå»?CLAUDE.md æä»¶ï¼åå«é¡¹ç®æååä¸ä¸æä¿¡æ¯\n"
        "Will create CLAUDE.md file with project guidelines and context",
        border_style="cyan"
    ))
    
    project_name = Prompt.ask(
        "é¡¹ç®åç§° / Project name",
        default=cwd.name
    )
    
    description = Prompt.ask(
        "é¡¹ç®æè¿° / Project description",
        default=""
    )
    
    content = f"""# {project_name}

{description}

## é¡¹ç®ç»æ / Project Structure

æ­¤é¡¹ç®ä½¿ç?AloneChat è¿è¡å¼åã?This project is developed using AloneChat.

## å¼åæå?/ Development Guidelines

- éµå¾ªä»£ç é£æ ¼è§è / Follow code style guidelines
- ç¼åæ¸æ°çæ³¨é?/ Write clear comments
- ä¿æä»£ç ç®æ´?/ Keep code simple

## ææ¯æ  / Tech Stack

- Python 3.10+
- AloneChat CLI

---
*ç?AloneChat èªå¨çæ / Generated by AloneChat*
"""
    
    claude_md.write_text(content, encoding="utf-8")
    console.print(f"\n[green]â?å·²åå»?/ Created: {claude_md}[/green]")
